// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sg_smooth_cpp
NumericMatrix sg_smooth_cpp(NumericMatrix x, int window_size, int order, int deriv, int n_cores);
RcppExport SEXP _ICEbox_sg_smooth_cpp(SEXP xSEXP, SEXP window_sizeSEXP, SEXP orderSEXP, SEXP derivSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(sg_smooth_cpp(x, window_size, order, deriv, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// colSds_cpp
NumericVector colSds_cpp(NumericMatrix x, int n_cores);
RcppExport SEXP _ICEbox_colSds_cpp(SEXP xSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(colSds_cpp(x, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// rowCenter_cpp
NumericMatrix rowCenter_cpp(NumericMatrix x, int n_cores);
RcppExport SEXP _ICEbox_rowCenter_cpp(SEXP xSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(rowCenter_cpp(x, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// transform_ice_curves_cpp
NumericMatrix transform_ice_curves_cpp(NumericMatrix x, int method, int n_cores);
RcppExport SEXP _ICEbox_transform_ice_curves_cpp(SEXP xSEXP, SEXP methodSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_ice_curves_cpp(x, method, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// melt_ice_curves_cpp
NumericVector melt_ice_curves_cpp(NumericMatrix x, int n_cores);
RcppExport SEXP _ICEbox_melt_ice_curves_cpp(SEXP xSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(melt_ice_curves_cpp(x, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// derivative_cpp
NumericMatrix derivative_cpp(NumericMatrix x, NumericVector gridpts, int n_cores);
RcppExport SEXP _ICEbox_derivative_cpp(SEXP xSEXP, SEXP gridptsSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gridpts(gridptsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(derivative_cpp(x, gridpts, n_cores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ICEbox_sg_smooth_cpp", (DL_FUNC) &_ICEbox_sg_smooth_cpp, 5},
    {"_ICEbox_colSds_cpp", (DL_FUNC) &_ICEbox_colSds_cpp, 2},
    {"_ICEbox_rowCenter_cpp", (DL_FUNC) &_ICEbox_rowCenter_cpp, 2},
    {"_ICEbox_transform_ice_curves_cpp", (DL_FUNC) &_ICEbox_transform_ice_curves_cpp, 3},
    {"_ICEbox_melt_ice_curves_cpp", (DL_FUNC) &_ICEbox_melt_ice_curves_cpp, 2},
    {"_ICEbox_derivative_cpp", (DL_FUNC) &_ICEbox_derivative_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ICEbox(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
